apiVersion: serving.knative.dev/v1 # Current version of Knative
kind: Service
metadata:
  name: hyperflow-executor
  namespace: default # The namespace the app will use
spec:
  template:
    spec:
      containers:
        - image: gcr.io/hyperflow-280917/hyperflow # The URL to the image of the app

